import { toast } from 'react-hot-toast';
import { useState, useRef } from "react";
import { FolderOpen, FileText, UploadCloud, File, Download, Link as LinkIcon, Trash2, Search, Filter } from "lucide-react";
import { clsx } from "clsx";

export function FileManagementPage() {
  const [activeTab, setActiveTab] = useState<'all' | 'invoices' | 'reports' | 'employees'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [toastMsg, setToastMsg] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const showToast = (msg: string) => {
    setToastMsg(msg);
    setTimeout(() => setToastMsg(''), 4000);
  };

  const [files, setFiles] = useState([
    { id: 1, name: 'Invoice_1024.pdf', type: 'Invoice PDFs', size: '2.4 MB', date: '2026-06-16', linkedTo: 'فاتورة #1024', tab: 'invoices' },
    { id: 2, name: 'Q1_Financial_Report.xlsx', type: 'Report Exports', size: '1.1 MB', date: '2026-06-15', linkedTo: '-', tab: 'reports' },
    { id: 3, name: 'Employee_Contract_Ahmed.pdf', type: 'Employee Documents', size: '3.5 MB', date: '2026-06-10', linkedTo: 'أحمد محمود', tab: 'employees' },
    { id: 4, name: 'Receipt_0051.jpg', type: 'Attachments', size: '800 KB', date: '2026-06-09', linkedTo: 'مصروفات مكتبية', tab: 'all' },
  ]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const newFile = {
        id: Date.now(),
        name: file.name,
        type: 'Attachments',
        size: `${(file.size / 1024 / 1024).toFixed(2)} MB`,
        date: new Date().toISOString().split('T')[0],
        linkedTo: '-',
        tab: 'all'
      };
      setFiles([newFile, ...files]);
      showToast(`تم رفع الملف ${file.name} بنجاح`);
    }
  };

  const handleDelete = (id: number, name: string) => {
    if (window.confirm(`هل أنت متأكد من حذف الملف ${name}؟`)) {
      setFiles(files.filter(f => f.id !== id));
      showToast(`تم حذف الملف ${name} بنجاح`);
    }
  };

  const handleDownload = (file: { id: number, name: string, type: string, size: string, date: string, linkedTo: string }) => {
    showToast(`جاري تحميل الملف ${file.name}...`);
    
    const reportContent = `=========================================
Bohemian Accounting System - File Export
=========================================

File Details:
-------------
Name         : ${file.name}
Type         : ${file.type}
Size         : ${file.size}
Upload Date  : ${file.date}
Linked To    : ${file.linkedTo}
System ID    : ${file.id}

Status       : Verified & Secure
Exported On  : ${new Date().toLocaleString('ar-EG')}

=========================================
(This document was auto-generated by the Bohemian System)
`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${file.name}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const normalizeText = (text: string) => text.replace(/[أإآ]/g, 'ا').replace(/[ةه]/g, 'ه').replace(/[ىي]/g, 'ي').toLowerCase();

  const filteredFiles = files.filter(f => {
    const matchesTab = activeTab === 'all' ? true : f.tab === activeTab;
    const matchesSearch = normalizeText(f.name).includes(normalizeText(searchQuery)) || normalizeText(f.linkedTo).includes(normalizeText(searchQuery));
    return matchesTab && matchesSearch;
  });

  const tabs = [
    { id: 'all', name: 'كل الملفات (Attachments)', icon: FolderOpen },
    { id: 'invoices', name: 'فواتير (Invoice PDFs)', icon: FileText },
    { id: 'reports', name: 'تقارير (Report Exports)', icon: File },
    { id: 'employees', name: 'مستندات الموظفين', icon: File },
  ] as const;

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="font-bold text-slate-800 text-2xl flex items-center gap-2"><FolderOpen className="w-7 h-7 text-primary-600"/> إدارة الملفات (File Management)</h2>
          <p className="text-slate-500 mt-1">إدارة المرفقات، المستندات، التقارير المصدرة، والسجلات المرتبطة (Linked Records).</p>
        </div>
        <div>
          <input 
            type="file" 
            ref={fileInputRef} 
            onChange={handleFileUpload} 
            className="hidden" 
          />
          <button 
             onClick={() => fileInputRef.current?.click()}
             className="bg-primary-600 text-white font-bold py-2 px-6 rounded-xl flex items-center gap-2 hover:bg-primary-700 transition shadow-sm"
          >
             <UploadCloud className="w-5 h-5"/> رفع ملف (Upload Files)
          </button>
        </div>
      </div>

      <div className="flex bg-slate-100 p-1 rounded-xl w-max overflow-x-auto">
        {tabs.map(tab => (
           <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={clsx(
                 "px-4 py-2 rounded-lg text-sm font-bold flex items-center gap-2 transition whitespace-nowrap",
                 activeTab === tab.id ? "bg-white text-primary-700 shadow-sm" : "text-slate-500 hover:text-slate-700"
              )}
           >
              <tab.icon className="w-4 h-4"/> {tab.name}
           </button>
        ))}
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
          <div className="relative w-full max-w-md">
            <Search className="w-5 h-5 absolute end-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input 
              type="text" 
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="بحث باسم الملف أو السجل المرتبط..." 
              className="w-full bg-white border border-slate-200 rounded-xl pe-10 ps-4 py-2 focus:outline-none focus:ring-2 focus:ring-primary-500 transition-all text-sm"
            />
          </div>
          <button 
            onClick={() => toast.success('تم تطبيق الفلتر بنجاح')} 
            className="p-2 border border-slate-200 bg-white rounded-xl text-slate-500 hover:bg-slate-50 transition ms-2"
          >
            <Filter className="w-5 h-5" />
          </button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-start text-sm">
            <thead className="bg-slate-50 text-slate-400 font-bold uppercase text-[10px] border-b border-slate-100">
              <tr>
                <th className="px-6 py-4 text-start">اسم الملف</th>
                <th className="px-6 py-4 text-start">النوع</th>
                <th className="px-6 py-4 text-start">الحجم</th>
                <th className="px-6 py-4 text-start">تاريخ الرفع</th>
                <th className="px-6 py-4 text-start">مرتبط بـ (Linked Records)</th>
                <th className="px-6 py-4 text-end">الإجراءات</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredFiles.map(file => (
                <tr key={file.id} className="hover:bg-slate-50 transition">
                  <td className="px-6 py-4 font-bold text-slate-800 flex items-center gap-3">
                    <FileText className="w-5 h-5 text-primary-400" />
                    {file.name}
                  </td>
                  <td className="px-6 py-4">
                    <span className="bg-slate-100 text-slate-600 px-2 py-1 rounded text-xs font-bold">{file.type}</span>
                  </td>
                  <td className="px-6 py-4 text-slate-500 font-mono text-xs">{file.size}</td>
                  <td className="px-6 py-4 text-slate-500 font-mono text-xs">{file.date}</td>
                  <td className="px-6 py-4">
                    {file.linkedTo !== '-' ? (
                      <span className="inline-flex items-center gap-1 text-primary-600 bg-primary-50 px-2 py-1 rounded text-xs font-bold cursor-pointer hover:underline">
                        <LinkIcon className="w-3 h-3" /> {file.linkedTo}
                      </span>
                    ) : (
                      <span className="text-slate-400">-</span>
                    )}
                  </td>
                  <td className="px-6 py-4 text-end">
                    <div className="flex items-center justify-end gap-2">
                      <button 
                        onClick={() => handleDownload(file)}
                        className="p-1.5 text-slate-400 hover:text-primary-600 hover:bg-primary-50 rounded transition" title="تحميل"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => handleDelete(file.id, file.name)}
                        className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded transition" title="حذف"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {toastMsg && (
        <div className="fixed bottom-10 start-1/2 -translate-x-1/2 bg-slate-900 text-white px-6 py-3 rounded-xl text-sm font-bold shadow-2xl z-[9999] whitespace-nowrap flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></div>
          {toastMsg}
        </div>
      )}
    </div>
  );
}
